version: '1'

services:
  MariaDB:
    image: mariadb:10.6.14
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=AguasFormosa
  MongoDB:
    image: mongo
    ports:
      - 27017:27017
    restart: on-failure
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=AguasFormosa
      - ME_CONFIG_BASICAUTH_USERNAME=AFuser
      - ME_CONFIG_BASICAUTH_PASSWORD=AFpass

  api_aguas_formosa:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - MariaDB
      - MongoDB
    restart: on-failure
    environment:
      - PORT=4000
      - DB_HOST_MARIADB=MariaDB
      - DB_PORT_MARIADB=3306
      - DB_USER_MARIADB=root
      - DB_PASSWORD_MARIADB=mysecretpassword
      - DB_DATABASE_MARIADB=AguasFormosa 
      - MONGODB_URI=mongodb://MongoDB:27017/AguasFormosa